FROM vcr.vngcloud.vn/111480-abp114553/m-credit-360:v6
COPY agents/eb_credit_agent.py /app/agents/eb_credit_agent.py
COPY agents/retail_credit_agent.py /app/agents/retail_credit_agent.py
COPY agents/credit_memo_builder_agent.py /app/agents/credit_memo_builder_agent.py
COPY agents/policy_eligibility_agent.py /app/agents/policy_eligibility_agent.py
COPY agents/statement_analyzer_agent.py /app/agents/statement_analyzer_agent.py
COPY agents/export_credit_memo_docx.py /app/agents/export_credit_memo_docx.py
COPY server.py /app/server.py
COPY zalo_bot_service.py /app/zalo_bot_service.py
COPY templates/index.html /app/templates/index.html
COPY requirements.txt /app/requirements.txt
